name: Mirror and run GitLab CI

on: [push]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Mirror and trigger CI
        uses: ./.github/actions/gitlab-ci
        with:
          args: https://gitlab.com/pydemic/capacidade_hospitalar
        env:
          GITLAB_USERNAME: ${{ secrets.GITLAB_USERNAME }}
          GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
