name: Trigger GitLab CI
on: [push]

jobs:
  push:
    - name: Trigger Job
      uses: appleboy/gitlab-ci-action@master
      with:
        url: "https://gitlab.com"
        token: ${{ secrets.TOKEN }}
        debug: true
        project_id: 18009514
        ref: ${GITHUB_REF##*/}
