name: Mirror and run GitLab CI

on: [push]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Mirror and trigger CI
        uses: SvanBoxel/gitlab-mirror-and-ci-action@master
        with:
          args: https://gitlab.com/pydemic/capacidade_hospitalar
        env:
          GITLAB_HOSTNAME: gitlab.com
          GITLAB_USERNAME: ${{ secrets.GITLAB_USERNAME }}
          GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
          GITLAB_PROJECT_ID: '18009514'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
